application: tdc2012app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: urls.app
 
libraries:
- name: jinja2
  version: "2.6"
- name: django
  version: "latest"

inbound_services:
- mail
- warmup

builtins:
- appstats: on